apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
  namespace: monitoring
data:
  zabbix_agent2.conf: |
    # This is a configuration file for Zabbix agent 2 (Unix)
    # To get more information about Zabbix, visit http://www.zabbix.com

    ############ GENERAL PARAMETERS #################
    PidFile=/var/run/zabbix/zabbix_agent2.pid
    LogFile=/var/log/zabbix/zabbix_agent2.log
    LogFileSize=0
    Server=zabbix-proxy.monitoring.svc.cluster.local
    #ListenIP=zabbix-agent-0
    HostInterface=zabbix-agent-0
    ##### Active checks related
    ServerActive=zabbix-proxy.monitoring.svc.cluster.local:10051
    Hostname=zabbix-agent-0
    Include=/etc/zabbix/zabbix_agent2.d/*.conf
    ControlSocket=/tmp/agent.sock
    # Include configuration files for plugins
    Include=./zabbix_agent2.d/plugins.d/*.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-supervisord
  namespace: monitoring
data:
  supervisord.conf: |

    [supervisord]
    nodaemon=true
    logfile=/var/log/supervisord.log
    logfile_maxbytes=50MB
    logfile_backups=10
    loglevel=info
    pidfile=/var/run/supervisord.pid
    childlogdir=/var/log/supervisor

    [program:zabbix_agent2]
    command=/usr/sbin/zabbix_agent2 -c /etc/zabbix/zabbix_agent2.conf
    autostart=true
    autorestart=true
    process_name=%(program_name)s
    redirect_stderr=false
    redirect_stdout=false
    stdout_logfile = /var/log/supervisor/zabbix_agent2.log
    stdout_logfile_maxbytes=10MB
    stdout_logfile_backups=10
    stderr_logfile = /var/log/supervisor/zabbix_agent2.log
    stderr_logfile_maxbytes=10MB
    stderr_logfile_backups=10
    stopsignal=INT
    startretries=3
    user=zabbix
    priority=999