apiVersion: v1
kind: Service

metadata:
  namespace: monitoring
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: zabbix-agent
    app: zabbix-agent 
  name: zabbix-agent
spec:
  ports:
  - name: "10050"
    port: 10050
    targetPort: 10050
  selector:
    zabbix-app: zabbix-agent
status:
  loadBalancer: {}
