
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: zabbix
  name: zabbix-service-account
  namespace: monitoring
secrets:
  - name: zabbix-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zabbix-clusterrole
  labels:
    app: zabbix
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - namespaces
      - endpoints 
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: zabbix
  name: zabbix-cr-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zabbix-clusterrole
subjects:
- kind: ServiceAccount
  name: zabbix-service-account
  namespace: monitoring